### ISSUE TITLE
Generate Random Strings Automatically

### ISSUE THREAD

**Issue by dabbadboiboss** [jrebocho/vscode-random#48]
Hi,
I'm new to VS Code and I found this extension. I wanted to know, is there a way to generate strings automatically? Sorry if this is obvious or something 😐
Thanks

**Comment by jrebocho** [comment]
Hi @dabbadboiboss ,

If I understood correctly, you should be able to generate strings with custom length using this extension with the following commands:

* Random letters
* Random digits
* Random letters and digits
* Random lowercase letters
* Random lowercase letters and digits
* Random uppercase letters
* Random uppercase letters and digits

Hope that this helps!
